### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by WuShenghui** [stanleycyang/react-bible-boilerplate#6]
When in step: npm run dev

const http = require('http')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by AlexanderCube19** [comment]
@kopijunkie solved this for me :)

**Comment by stanleycyang** [comment]
@WuShenghui what version of NodeJS are you using?

**Comment by AlexanderCube19** [comment]
v4.2.2

**Comment by WuShenghui** [comment]
@stanleycyang  my NodeJs version is 0.12.6

**Comment by stanleycyang** [comment]
@WuShenghui upgrade to Node V4 or higher and your problem should go away

**Comment by WuShenghui** [comment]
@stanleycyang  Yes, That was my NodeJs version too low, upgrade to the latest it work fine, thanks for your help.
